name: Deploy Simple Mode (Custom Domain)

on:
  workflow_dispatch:
  # Optional: schedule triggers
  # schedule:
  #   - cron: '0 0 * * 0'

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # 1. Checkout the OFFICIAL BentoPDF repository
      - name: Checkout Upstream BentoPDF
        uses: actions/checkout@v4
        with:
          repository: alam00000/bentopdf
          ref: main

      # 2. Setup Node.js
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      # 3. Install Dependencies
      - name: Install Dependencies
        run: npm ci

      # 4. Build in Simple Mode
      # Note: We do NOT need to change the base path for custom domains.
      # The default root path is exactly what we want.
      - name: Build Simple Mode
        run: npm run build
        env:
          SIMPLE_MODE: true
          VITE_SIMPLE_MODE: true

      # 5. Create CNAME file for Custom Domain
      # This tells GitHub Pages which domain to serve
      - name: Create CNAME
        run: echo "pdf.git.icc.gg" > dist/CNAME

      # 6. Fix 404 Routing
      - name: Fix 404 Routing
        run: cp dist/index.html dist/404.html

      # 7. Deploy to YOUR repository's gh-pages branch
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          force_orphan: true
